data/enums
Avila-Tek/avilatek-mobile-docs pull request #16
Opened 2024-08-20 17:39 UTC by Vizten18

2024-08-23 16:08 UTC, andrespd99 requested changes
Nota general:

Corrige las identaciones de todos los ejemplos. Te recomiendo que escribas el ejemplo en un archivo Dart y luego de formatearlo lo pegues tal cual en el md.


![image](https://github.com/user-attachments/assets/a6a40a84-cbac-4a9b-9ddd-fbf8aea9cd22)

Por ejemplo:

Este ejemplo
```md
    enum ItemCollectionEnum implements BaseEnum<ItemCollection, String> {
    post('post'),
    book('book'),
    track('track'),
    unknown('unknown');
    }
```

debería ser así
```md
enum ItemCollectionEnum implements BaseEnum<ItemCollection, String> {
  post('post'),
  book('book'),
  track('track'),
  unknown('unknown');
}
```

![image](https://github.com/user-attachments/assets/5f601716-e340-44b9-b46d-61866a0daacc)

2024-08-23 16:08 UTC, andrespd99 commented on docs/code-rules/data/enums.md
> +      const PrivacyTypeEnum(this.value);
Estás usando el constructor de otra clase acá (PrivacyTypeEnum, no ItemCollectionEnum)

Recuerda que los vamos a llamar "...Model", no "...Enum".

Pon primero el constructor y debajo el atributo value.

El ejemplo está bueno, te diría que agregues un segundo ejemplo con ints para cédulas (que es común en nuestros proyectos):

```dart
enum DocumentTypeModel implements BaseEnum<DocumentType, Int> {
  v(1),
  j(2)
  e(3),        
  g(4);
        
  const DocumentTypeModel(this.value);
  final String value;
}
```

Nota: Ten cuidado con las indentaciones. El parser markdown no las corrige por ti. Te recomiendo que lo escribas en un archivo dart y copies y pegues el ejemplo directamente de ahí

2024-08-23 19:44 UTC, Vizten18 commented on docs/code-rules/data/enums.md
> +Es fundamental que, al crear enumeradores, se implemente correctamente la interfaz `BaseEnum<E, T>`. Esta implementación permite estandarizar y sobrescribir los métodos `fromValue` y `toEntity`, aseg
ok perfecto, luego nos ponemos con ese link cuando esa opagina esté habilitada

2024-08-23 19:45 UTC, Vizten18 commented on docs/code-rules/data/enums.md
> +```dart title="Regla de nombrado de clases"
Lo cambié, ya no será Enum, ahora será model e identifico que ahora la carpeta enums de data estará dentro de models con una subcarpeta llamada enums

2024-08-23 19:46 UTC, Vizten18 commented on docs/code-rules/data/enums.md
> +El método toEntity nos permite convertir nuestro enum o modelo de data y llevarlo a la capa de dominio para su uso sencillo en la aplicación.
Coye que brutal esto jsjs

2024-08-23 19:47 UTC, Vizten18 commented on docs/code-rules/data/enums.md
> +````
ups... acomodado

2024-08-26 19:31 UTC, andrespd99 requested changes

2024-08-26 19:31 UTC, andrespd99 commented on docs/code-rules/data/enums.md
> +````
Son tres (```) backticks, no cuatro

2024-08-26 19:31 UTC, andrespd99 commented on docs/code-rules/data/enums.md
Todos los bloques de código tienen una indentación de más. Mira este ejemplo

```md
    enum ItemCollectionModel implements BaseEnum<ItemCollectionEnum, String> {} // Implementación de BaseEnum
    enum PrivacyTypeModel implements BaseEnum<PrivacyType, String> {}
```

Esto debería estar asi

```md
enum ItemCollectionModel implements BaseEnum<ItemCollectionEnum, String> {} // Implementación de BaseEnum
enum PrivacyTypeModel implements BaseEnum<PrivacyType, String> {}
```

Revisa bien todos los bloques de código y reduce un nivel de indentación de todos los bloques (selecciona el bloque y haz Shift + Tab  una vez)

2024-08-26 19:31 UTC, andrespd99 commented on docs/code-rules/data/enums.md
> +### Atributo value
Pon la palabra value entre backticks (`value`) porque es una variable de código.

2024-08-26 20:40 UTC, Vizten18 commented on docs/code-rules/data/enums.md
> +Los parámetros de los constructores en los enumeradores **deben** reflejarse dentro de las llaves de inicialización. Según la regla, primero se debe colocar el nombre del parámetro, seguido del valor
cambiado

2024-08-26 21:07 UTC, andrespd99 commented on docs/code-rules/data/enums.md
> +enum ItemCollectionModel implements BaseEnum<ItemCollectionEnum, String> {} // Implementación de BaseEnum
No me queda claro el comentario 
```
// Implementación de BaseEnum
```

2024-08-26 21:18 UTC, andrespd99 commented on docs/code-rules/data/enums.md
> +#### A. Casos en los que el valor venga con un guión
Replantea este inciso como "Formato camelCase" y el artículo hazlo más genérico. Esto aplica no solo para guiones, tambien para underscore `_`, espacios en blanco, etc. Incluso tus nombres pueden no tener nada que ver con la variable. Por esa razón, es mejor que tu artículo diga algo mucho más general como

```
Los valores de los enumeradores **deben** definirse en camel case.
```

2024-08-26 21:19 UTC, andrespd99 commented on docs/code-rules/data/enums.md
> +```dart title="Inicialización de enum con Int"
Este ejemplo no está relacionado con el inciso. Remover

2024-08-26 21:20 UTC, andrespd99 commented on docs/code-rules/data/enums.md
> +  unknown('unknown');
El `value` de unknown debería ser un espacio en blanco `''`

2024-08-26 21:22 UTC, andrespd99 commented on docs/code-rules/data/enums.md
> +```dart title="Método fromValue"
Mueve este ejemplo bajo el inciso A porque creo que tiene mas sentido mostrarlo despues del inciso A que habla del parámetro `orElse` y que usas en este ejemplo.

2024-08-26 21:25 UTC, andrespd99 commented on docs/code-rules/data/enums.md
> +  throw Exception('Invalid ItemCollection'); //Podemos devolver una excepcion normal o una excepcion personalizada
El ejemplo está incompleto. No excluyas partes del código que sean importantes para el contexto. En este caso incluye el enum y la función (`fromEntity`) que encierra este pedazo de código

2024-08-26 21:27 UTC, andrespd99 commented on docs/code-rules/data/enums.md
> +  final String value;
Pon el atributo debajo del constructor (así es la regla de nuestro linter)

2024-08-26 21:28 UTC, andrespd99 commented on docs/code-rules/data/enums.md
> +Este atributo estará para recibir y/o enviar el valor que estemos manejando de nuestro enum.
Sigue faltando aplicar esta revisión

2024-08-26 21:41 UTC, Vizten18 commented on docs/code-rules/data/enums.md
> +enum ItemCollectionModel implements BaseEnum<ItemCollectionEnum, String> {} // Implementación de BaseEnum
cambié la redaccion explicando como implementar BaseEnum

2024-08-29 17:08 UTC, andrespd99 requested changes
Muy bien chente! Te dejé un par de comentarios pequeños pero el capítulo está muchisimo mejor! Luego de estos cambios considero que estaría listo el cap

2024-08-29 17:08 UTC, andrespd99 commented on docs/code-rules/data/enums.md
> +Los parámetros de los constructores en los enumeradores **deben** reflejarse dentro de las llaves de inicialización. Primero se coloca el nombre del parámetro, seguido del valor correspondiente en ba
"[...] ~en base al~ con base en el tipo de dato [...]"

Está mal dicha la expresión "en base a _". La forma correcta es "con base en _".

2024-08-29 17:08 UTC, andrespd99 commented on docs/code-rules/data/enums.md
> +  spam('spam'),
Incluye la definición del enum en el ejemplo. No excluyas partes del código importantes para entender el ejemplo aunque sea redundante con los ejemplos anteriores. Una regla de pulgar es que tus ejemplos se puedan entender sin haber leído ningún articulo ni ejemplo previo en el capítulo.

2024-08-29 17:12 UTC, andrespd99 requested changes

2024-08-29 17:12 UTC, andrespd99 commented on docs/code-rules/data/enums.md
> +Si no queremos devolver un valor de manera predeterminada podemos manejar excepciones en nuestro enum.
Me marcaste como resolved este comentario pero sigue teniendo redacción personal jajaja. Revisa bien antes de marcar como resuelta las observaciones.

https://github.com/Avila-Tek/avilatek-mobile-docs/pull/16/files#r1729186022

2024-08-29 21:34 UTC, Vizten18 commented on docs/code-rules/data/enums.md
> +Los enumeradores **deben** implementar la interfaz `BaseEnum<E, T>` estableciendo la palabra clave `implements` despues del nombrado del `Enum`.
done

2024-08-29 21:37 UTC, Vizten18 commented on docs/code-rules/data/enums.md
> +Si no queremos devolver un valor de manera predeterminada podemos manejar excepciones en nuestro enum.
lo cambié asi

"Para evitar devolver un valor predeterminado, se pueden manejar excepciones dentro del enumerador."

2024-09-11 16:58 UTC, andrespd99 requested changes
Chente está todo perfecto. Solo falta corregir la redacción del artículo del atributo value y estamos listos por aquí.

2024-09-11 16:58 UTC, andrespd99 commented on docs/code-rules/data/enums.md
> +Este atributo estará para recibir y/o enviar el valor que estemos manejando de nuestro enum.
Hacer la redacción impersonal
-> "El atributo `value` representa el valor equivalente de la fuente de datos."

2024-10-02 21:24 UTC, merged