domain enums
Avila-Tek/avilatek-mobile-docs pull request #22
Opened 2024-08-23 20:27 UTC by Vizten18

2024-09-09 15:58 UTC, andrespd99 requested changes

2024-09-09 15:58 UTC, andrespd99 commented on docs/code-rules/domain/enums.md
> +Los enumeradores en la capa de dominio **deben** tener el mismo nombre base relacionado a su entidad, correspondiente al uso que tendrá y nombrarse en singular. Algunos ejemplos de nombres de enumera
> Los enumeradores en la capa de dominio **deben** tener el mismo nombre base relacionado a _su entidad_ ...

Chente, la entidad es el enumerador en sí jeje. Hay que actualizar el enunciado un poco

2024-09-09 15:58 UTC, andrespd99 commented on docs/code-rules/domain/enums.md
> +Los parámetros de los enumeradores **deben** ser iguales a los valores que vengan directamente de la fuente de datos original. En caso de que dicho valor proveniente del servidor contenga un guión de
Acá no hagas mención de la fuente de datos. La capa de dominio debe ser agnóstica a las otras capas.

Creo que podemos dejar únicamente la regla de que debe usarse el formato camelCase. De resto, no veo otra regla que debamos enforzar

2024-09-09 16:00 UTC, Vizten18 commented on docs/code-rules/domain/enums.md
> +Los enumeradores en la capa de dominio **deben** tener el mismo nombre base relacionado a su entidad, correspondiente al uso que tendrá y nombrarse en singular. Algunos ejemplos de nombres de enumera
Ahora solo mencionan que deben nombrarse correspondiente al uso que tendrá

2024-09-11 17:02 UTC, andrespd99 approved these changes

2024-10-02 21:27 UTC, merged