presentation/blocs
Avila-Tek/avilatek-mobile-docs pull request #23
Opened 2024-09-09 16:01 UTC by ortegadn

2024-09-11 18:19 UTC, andrespd99 requested changes
Pepa pig

2024-09-11 18:19 UTC, andrespd99 commented on docs/code-rules/presentation/blocs.md
> +- **Como atributo privado:** en este caso el parámetro recibido en el constructor se guarda en un atributo `final` **privado** definido en el Bloc.
Otra nota, no necesariamente tiene que ser privado. A veces es válido (incluso útil) que sea público. Por ejemplo si quieres guardar el ID de un objeto en el bloc y accederlo desde el widget, lo puedes hacer como:

```dart
final id = context.read<FooBloc>().someId;
```

Así que plantea esta idea sin limitar a que sea privada o pública. Si te parece valioso, puedes explicar esos escenarios donde es válido que sea publico o privado

2024-09-11 18:19 UTC, andrespd99 commented on docs/code-rules/presentation/blocs.md
> +Los Blocs solo **deben** recibir casos de uso (definidos en la capa de dominio) para manejar la logica de negocio del feature, y **deben** ser asignados obligatoriamente a atributos privados dentro d
Pon Casos de Uso en mayúscula y agregale un link

Acá te dejo la doc para links entre páginas de docusaurus https://docusaurus.io/docs/markdown-features/links

2024-09-11 18:19 UTC, andrespd99 commented on docs/code-rules/presentation/blocs.md
> + **Está prohibida la interdependencia de Blocs** (paso de un Bloc a otro por parámetro). La comunicación entre Blocs **debe** hacerse por medio de `BlocListeners` o directamente accediendo a ellos po
A la parte de la comunicación entre blocs puedes agregarle el preámbulo de que se debe hacer desde afuera, y luego mencionas lo de BlocListeners o por medio del contexto.

Por ejemplo:
"[...] La comunicación entre Blocs debe hacerse desde fuera; por ejemplo, mediante la emisión de eventos como respuesta del cambio de estado de otro bloc con el uso de `BlocListeners`, o accediendo a la instancia de los blocs por contexto con los métodos `context.read`, `context.watch` o `context.select` [...]"

Algo por el estilo, es solo una idea.

2024-09-11 18:19 UTC, andrespd99 commented on docs/code-rules/presentation/blocs.md
> +El constructor de la clase registra varios manejadores de eventos utilizando el método `on<Event>(FutureOr<void> Function(E, Emitter<State>) handler, {Stream<E> Function(Stream<E>, Stream<E> Function
Esto no se lee bien en el doc. Creo que es mejor que metas eso en un bloque de código por separado (triple `)

2024-09-11 18:19 UTC, andrespd99 commented on docs/code-rules/presentation/blocs.md
> +}
Agrega al ejemplo la función close del bloc y del listener

2024-09-17 14:14 UTC, ortegadn commented on docs/code-rules/presentation/blocs.md
> + **Está prohibida la interdependencia de Blocs** (paso de un Bloc a otro por parámetro). La comunicación entre Blocs **debe** hacerse por medio de `BlocListeners` o directamente accediendo a ellos po
Me gusta la idea

2024-09-19 20:16 UTC, andrespd99 requested changes
¡Todo espectacular Erick! Top la documentación de Bloc

2024-09-19 20:16 UTC, andrespd99 commented on docs/code-rules/presentation/blocs.md
> +- `handler` hace referencia al [manejador del evento](#manejadores-de-eventos). Siempre **debe** ser privado y solo se **debe** referenciar en el constructor. El cuerpo de la función **será** definid
Si quieres resaltar la obligación de definir el cuerpo de la función dentro de la clase, puedes hacerlo de la siguiente manera:

```md
[...] El cuerpo de la función **debe** ser definido dentro de la clase, no del constructor.
 ```
 
Así también mantenemos la cohesión de la regla del resaltado del verbo

2024-09-19 20:40 UTC, andrespd99 approved these changes

2024-10-02 21:24 UTC, merged