data/repositories
Avila-Tek/avilatek-mobile-docs pull request #27
Opened 2024-09-11 14:18 UTC by Vizten18

2024-09-11 17:43 UTC, andrespd99 requested changes

2024-09-11 17:43 UTC, andrespd99 commented on docs/code-rules/data/repositories.md
> +El repositorio luego de su nombramiento **debe** incluir la extensión de su interfaz de la capa de dominio agregando `extends` despues de nombrarlo.
No expliques el como, solo el qué:
"La clase repositorio de la capa de datos debe extender de la interfaz repositorio de la capa dominio", o algo por el estilo.

2024-09-11 17:43 UTC, andrespd99 commented on docs/code-rules/data/repositories.md
> +El repositorio **debe** inicializar sus dependencias a través de una variable y luego instanciarse a través del constructor.
Yo a esto lo llamo parámetros delegados. Es el delegado de recibir el valor en el constructor y luego asignarselo al atributo privado de la clase.

Reformulemos un poco el artículo para que sea mas claro:
"El repositorio debe recibir las variables y dependencias como parámetros delegados y asignarlos a los atributos privados respectivos de la clase en el constructor."

2024-09-11 17:43 UTC, andrespd99 commented on docs/code-rules/data/repositories.md
> +Los streams **deben** tener la siguiente estructura.
Explica un poco más la estructura en el artículo. Streams es un tipo de dato, así que metelo en backticks:

```md
Los `Streams` **deben** declararse como getters del atributo stream de un `StreamController` que controle el flujo de información en el repositorio. La variable del `StreamController` **debe** ser privada.
```

Nota: Si quieres incluye el Sink, aunque yo no forzaría como una regla.

2024-09-11 17:43 UTC, andrespd99 commented on docs/code-rules/data/repositories.md
> +El repositorio **puede** declarar variables públicas para el uso global del proyecto y variables privadas para uso interno del archivo.
Las variables públicas en los repositorios de data tienen que ser parte de la interfaz (del repo en dominio), así que en teoría esos atributos deberían ser getters. Vamos a separar esto en dos artículos:

1. Atributos privados
```md
Los atributos de uso interno de la clase, como dependencias y variables auxiliares, **deben** ser atributos privados.
```

2. Atributos públicos
```md
Los atributos públicos que sean parte de la firma de la interfaz del repositorio **deben** declararse como getters de atributos privados.
```
Razon de esto: Para que el usecase pueda acceder a los atributos públicos tienen que ser parte de la interfaz (recuerda que lo que pasas por parámetro es la interfaz, nunca el repositorio en concreto). Por otro lado, es buena práctica que sea un getter y no una variable pública para que nada externo pueda modificarlo.

Algo así se vería el ejemplo:

```dart
abstract class IUserRepository {
   List<Country> countries;
}

class UserRepository extends IUserRepository {
  List<Country> _countries = <Country>[];
  @override
  List<Country> get countries => _countries;
}
```

Nota: Ve que en el ejemplo incluí el código de la interfaz. Acá es valioso agregarlo en el ejemplo para que el lector tenga más contexto de lo que se está explicando.

2024-09-11 17:43 UTC, andrespd99 commented on docs/code-rules/data/repositories.md
> +Los repositorios **pueden** tener inicializaciones y ejecuciones de streams.
Creo que esto queda obsoleto con el otro comentario

2024-09-11 17:43 UTC, andrespd99 commented on docs/code-rules/data/repositories.md
> +La función `Sink` del stream a utilizar **debe** implementarse luego de la llamada de la función para que el nuevo valor sea implementado al stream.
No me convence mucho este apartado. Recuerdo que con casos de uso nos referíamos a una lista de aplicaciones para los streams en el código aunque todos se pueden reducir a un solo caso de uso:  "Escuchar cambios en la aplicación."

Vamos a remover este artículo

2024-09-11 17:43 UTC, andrespd99 commented on docs/code-rules/data/repositories.md
> +#### B. Variable \_source
Envuelve _source en backticks `` 
Y no va a ser necesario el backslash \

2024-09-11 17:43 UTC, andrespd99 commented on docs/code-rules/data/repositories.md
> +Al momento de iniciar una llamada debe registrarse los pasos de ejecución de la siguiente manera:
Agrega en el artículo el uso de los emojis 📡, ✅ y ❌

2024-09-11 17:43 UTC, andrespd99 commented on docs/code-rules/data/repositories.md
> +        stackTrace: s,
Sería bueno incluir un inciso o parte del artículo el pasar el error y stacktrace a los logs del catch

2024-09-11 17:43 UTC, andrespd99 commented on docs/code-rules/data/repositories.md
> +    /// Vamos a identificar si existe una excepcion personalisada en la cual
"personalisada" Está mal escrito, es "personalizada" con z

2024-09-11 17:43 UTC, andrespd99 commented on docs/code-rules/data/repositories.md
> +    /// Vamos a identificar si existe una excepcion personalisada en la cual
Reescribe los comentarios en forma impersonal también

2024-09-11 23:28 UTC, Vizten18 commented on docs/code-rules/data/repositories.md
> +Los repositorios **pueden** tener inicializaciones y ejecuciones de streams.
Si, eliminado

2024-09-11 23:29 UTC, Vizten18 commented on docs/code-rules/data/repositories.md
> +La función `Sink` del stream a utilizar **debe** implementarse luego de la llamada de la función para que el nuevo valor sea implementado al stream.
Eliminado

2024-09-11 23:29 UTC, Vizten18 commented on docs/code-rules/data/repositories.md
> +#### B. Variable \_source
error de tipado perdon

2024-09-11 23:35 UTC, Vizten18 commented on docs/code-rules/data/repositories.md
> +    /// Vamos a identificar si existe una excepcion personalisada en la cual
Alamierda, perdon eso fue un error de tipado duro jajaj, sé escribir te lo juro

2024-09-16 15:52 UTC, andrespd99 requested changes

2024-09-16 15:52 UTC, andrespd99 commented on docs/code-rules/data/repositories.md
> +Al momento de realizar el try/catch de la petición se **puede** pasar el parametro `e` y el `s` en el log del catch
```md
Se **deben** declarar los parámetros `error` y `stackTrace` del método `log()` en el bloque `catch` de la función.
```

2024-10-02 21:25 UTC, merged